function SearchAddressesPostcodeController ($scope) {

	var $addressEl = $scope.find('#addressAutocomplete'),
		$addressDetailsTrigger = $scope.find('#address-details-trigger'),
		$addressStartAgainTrigger = $scope.find('#address-start-again-trigger'),
		$details = $scope.find('#guidance-permanent-or-family-home-answer-body'),

		addressComponent = new TypeaheadComponent($('#locationField'), $addressEl),
		fieldToDataMap = {
			houseNameOrNumber: 'street_number',
			organisationName: 'organisation_name',
			streetAddress: 'route',
			cityTown: 'postal_town',
			county: 'county',
			postCode: 'postal_code',
			country: 'country'
		},
		mockData = [{
			"DPA" : {
				"UPRN" : "43014115",
				"UDPRN" : "4547315",
				"ADDRESS" : "1, WARE ROAD, CAERFFILI, CF83 1SX",
				"BUILDING_NUMBER" : "1",
				"THOROUGHFARE_NAME" : "WARE ROAD",
				"POST_TOWN" : "CAERFFILI",
				"POSTCODE" : "CF83 1SX",
				"RPC" : "1",
				"X_COORDINATE" : 314172.0,
				"Y_COORDINATE" : 186296.0,
				"STATUS" : "APPROVED",
				"LOGICAL_STATUS_CODE" : "1",
				"CLASSIFICATION_CODE" : "RD",
				"CLASSIFICATION_CODE_DESCRIPTION" : "Dwelling",
				"LOCAL_CUSTODIAN_CODE" : 6920,
				"LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "CAERPHILLY",
				"POSTAL_ADDRESS_CODE" : "D",
				"POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
				"BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
				"TOPOGRAPHY_LAYER_TOID" : "osgb1000027048446",
				"LAST_UPDATE_DATE" : "10/02/2016",
				"ENTRY_DATE" : "31/01/2003",
				"LANGUAGE" : "CY",
				"MATCH" : 0.2,
				"MATCH_DESCRIPTION" : "NO MATCH"
			}
		}, {
			"DPA" : {
				"UPRN" : "100100209509",
				"UDPRN" : "4650113",
				"ADDRESS" : "1, GREENACRE DRIVE, BAGILLT, CH6 6DY",
				"BUILDING_NUMBER" : "1",
				"THOROUGHFARE_NAME" : "GREENACRE DRIVE",
				"POST_TOWN" : "BAGILLT",
				"POSTCODE" : "CH6 6DY",
				"RPC" : "1",
				"X_COORDINATE" : 322637.53,
				"Y_COORDINATE" : 374544.52,
				"STATUS" : "APPROVED",
				"LOGICAL_STATUS_CODE" : "1",
				"CLASSIFICATION_CODE" : "RD02",
				"CLASSIFICATION_CODE_DESCRIPTION" : "Detached",
				"LOCAL_CUSTODIAN_CODE" : 6835,
				"LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "FLINTSHIRE",
				"POSTAL_ADDRESS_CODE" : "D",
				"POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
				"BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
				"TOPOGRAPHY_LAYER_TOID" : "osgb1000034471824",
				"LAST_UPDATE_DATE" : "10/02/2016",
				"ENTRY_DATE" : "10/05/2001",
				"LANGUAGE" : "CY",
				"MATCH" : 0.2,
				"MATCH_DESCRIPTION" : "NO MATCH"
			}
		}, {
			"DPA" : {
				"UPRN" : "200003767038",
				"UDPRN" : "4379366",
				"ADDRESS" : "1, POWELLS PLACE, PORTH, CF39 9RW",
				"BUILDING_NUMBER" : "1",
				"THOROUGHFARE_NAME" : "POWELLS PLACE",
				"POST_TOWN" : "PORTH",
				"POSTCODE" : "CF39 9RW",
				"RPC" : "1",
				"X_COORDINATE" : 302542.0,
				"Y_COORDINATE" : 191420.0,
				"STATUS" : "APPROVED",
				"LOGICAL_STATUS_CODE" : "1",
				"CLASSIFICATION_CODE" : "RD04",
				"CLASSIFICATION_CODE_DESCRIPTION" : "Terraced",
				"LOCAL_CUSTODIAN_CODE" : 6940,
				"LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "RHONDDA CYNON TAF",
				"POSTAL_ADDRESS_CODE" : "D",
				"POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
				"BLPU_STATE_CODE" : "2",
				"BLPU_STATE_CODE_DESCRIPTION" : "In use",
				"TOPOGRAPHY_LAYER_TOID" : "osgb1000023740817",
				"LAST_UPDATE_DATE" : "10/02/2016",
				"ENTRY_DATE" : "31/10/2002",
				"BLPU_STATE_DATE" : "28/08/2013",
				"LANGUAGE" : "CY",
				"MATCH" : 0.2,
				"MATCH_DESCRIPTION" : "NO MATCH"
			}
		}, {
			"DPA" : {
				"UPRN" : "10009180022",
				"UDPRN" : "21233518",
				"ADDRESS" : "1, DERLWYN, CASTELL-NEDD, SA10 7QU",
				"BUILDING_NUMBER" : "1",
				"THOROUGHFARE_NAME" : "DERLWYN",
				"POST_TOWN" : "CASTELL-NEDD",
				"POSTCODE" : "SA10 7QU",
				"RPC" : "2",
				"X_COORDINATE" : 274086.0,
				"Y_COORDINATE" : 198274.0,
				"STATUS" : "APPROVED",
				"LOGICAL_STATUS_CODE" : "1",
				"CLASSIFICATION_CODE" : "RD",
				"CLASSIFICATION_CODE_DESCRIPTION" : "Dwelling",
				"LOCAL_CUSTODIAN_CODE" : 6930,
				"LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "NEATH PORT TALBOT",
				"POSTAL_ADDRESS_CODE" : "D",
				"POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
				"BLPU_STATE_CODE" : "2",
				"BLPU_STATE_CODE_DESCRIPTION" : "In use",
				"TOPOGRAPHY_LAYER_TOID" : "osgb1000041956935",
				"LAST_UPDATE_DATE" : "10/02/2016",
				"ENTRY_DATE" : "05/05/2005",
				"BLPU_STATE_DATE" : "05/05/2005",
				"LANGUAGE" : "CY",
				"MATCH" : 0.2,
				"MATCH_DESCRIPTION" : "NO MATCH"
			}
		}, {
			"DPA" : {
				"UPRN" : "10023167356",
				"UDPRN" : "50316895",
				"ADDRESS" : "1, BENTLEY PLACE, WRECSAM, LL13 8DQ",
				"BUILDING_NUMBER" : "1",
				"THOROUGHFARE_NAME" : "BENTLEY PLACE",
				"POST_TOWN" : "WRECSAM",
				"POSTCODE" : "LL13 8DQ",
				"RPC" : "2",
				"X_COORDINATE" : 334126.66,
				"Y_COORDINATE" : 349882.63,
				"STATUS" : "APPROVED",
				"LOGICAL_STATUS_CODE" : "1",
				"CLASSIFICATION_CODE" : "RD06",
				"CLASSIFICATION_CODE_DESCRIPTION" : "Self Contained Flat (Includes Maisonette / Apartment)",
				"LOCAL_CUSTODIAN_CODE" : 6955,
				"LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "WREXHAM",
				"POSTAL_ADDRESS_CODE" : "D",
				"POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
				"BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
				"TOPOGRAPHY_LAYER_TOID" : "osgb1000002755046329",
				"LAST_UPDATE_DATE" : "10/02/2016",
				"ENTRY_DATE" : "14/04/2008",
				"LANGUAGE" : "CY",
				"MATCH" : 0.2,
				"MATCH_DESCRIPTION" : "NO MATCH"
			}
		}, {
			"DPA" : {
				"UPRN" : "100100001967",
				"UDPRN" : "13682465",
				"ADDRESS" : "10, GARREGLWYD PARK, CAERGYBI, LL65 1NW",
				"BUILDING_NUMBER" : "10",
				"THOROUGHFARE_NAME" : "GARREGLWYD PARK",
				"POST_TOWN" : "CAERGYBI",
				"POSTCODE" : "LL65 1NW",
				"RPC" : "1",
				"X_COORDINATE" : 223898.0,
				"Y_COORDINATE" : 382515.0,
				"STATUS" : "APPROVED",
				"LOGICAL_STATUS_CODE" : "1",
				"CLASSIFICATION_CODE" : "RD",
				"CLASSIFICATION_CODE_DESCRIPTION" : "Dwelling",
				"LOCAL_CUSTODIAN_CODE" : 6805,
				"LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "ISLE OF ANGLESEY",
				"POSTAL_ADDRESS_CODE" : "D",
				"POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
				"BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
				"TOPOGRAPHY_LAYER_TOID" : "osgb1000033999031",
				"LAST_UPDATE_DATE" : "10/02/2016",
				"ENTRY_DATE" : "30/05/2002",
				"LANGUAGE" : "CY",
				"MATCH" : 0.2,
				"MATCH_DESCRIPTION" : "NO MATCH"
			}
		},{
			"DPA" : {
				"UPRN" : "10011744354",
				"UDPRN" : "13036886",
				"ADDRESS" : "1, RIVERSIDE, LLYSWEN, ABERHONDDU, LD3 0LJ",
				"BUILDING_NUMBER" : "1",
				"THOROUGHFARE_NAME" : "RIVERSIDE",
				"DEPENDENT_LOCALITY" : "LLYSWEN",
				"POST_TOWN" : "ABERHONDDU",
				"POSTCODE" : "LD3 0LJ",
				"RPC" : "1",
				"X_COORDINATE" : 312995.53,
				"Y_COORDINATE" : 238327.04,
				"STATUS" : "APPROVED",
				"LOGICAL_STATUS_CODE" : "1",
				"CLASSIFICATION_CODE" : "RD02",
				"CLASSIFICATION_CODE_DESCRIPTION" : "Detached",
				"LOCAL_CUSTODIAN_CODE" : 6850,
				"LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "POWYS",
				"POSTAL_ADDRESS_CODE" : "D",
				"POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
				"BLPU_STATE_CODE" : "2",
				"BLPU_STATE_CODE_DESCRIPTION" : "In use",
				"TOPOGRAPHY_LAYER_TOID" : "osgb1000020865533",
				"LAST_UPDATE_DATE" : "10/02/2016",
				"ENTRY_DATE" : "14/10/2004",
				"BLPU_STATE_DATE" : "02/05/2012",
				"LANGUAGE" : "CY",
				"MATCH" : 0.2,
				"MATCH_DESCRIPTION" : "NO MATCH"
			}
		}],
		isOpen = false,
		keyEntryPace = {
			/*timeout: 3000,
			entries: [1000],
			record: function () {
				console.log(this);
			},*/
			get: function () {
				return 0;
			}
		};
}
